[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "swd1a-test-notebooks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.3,<3"
matplotlib = ">=3.10.0,<4"
jupyter = ">=1.1.1,<2"
